"""sprint_disponibilidad_delivery_favoritos_notificaciones

Revision ID: 0651eb7fe36d
Revises: h8c9d0e1f2g3
Create Date: 2026-05-28 01:51:33.389595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0651eb7fe36d'
down_revision: Union[str, Sequence[str], None] = 'h8c9d0e1f2g3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Tablas nuevas (IF NOT EXISTS — seguro en DB fresca)
    op.execute("""
        CREATE TABLE IF NOT EXISTS blocked_dates (
            id VARCHAR NOT NULL,
            asset_id VARCHAR NOT NULL REFERENCES assets(id),
            provider_id VARCHAR NOT NULL REFERENCES users(id),
            start_date TIMESTAMPTZ NOT NULL,
            end_date TIMESTAMPTZ NOT NULL,
            reason VARCHAR,
            created_at TIMESTAMPTZ,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_blocked_dates_asset_id ON blocked_dates (asset_id)")

    op.execute("""
        CREATE TABLE IF NOT EXISTS favorites (
            id VARCHAR NOT NULL,
            client_id VARCHAR NOT NULL REFERENCES users(id),
            asset_id VARCHAR NOT NULL REFERENCES assets(id),
            created_at TIMESTAMPTZ,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_favorites_client_id ON favorites (client_id)")

    op.execute("""
        CREATE TABLE IF NOT EXISTS notifications (
            id VARCHAR NOT NULL,
            user_id VARCHAR NOT NULL REFERENCES users(id),
            booking_id VARCHAR REFERENCES bookings(id),
            type VARCHAR NOT NULL,
            title VARCHAR NOT NULL,
            message TEXT NOT NULL,
            seen BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications (user_id)")

    # Columnas nuevas con server_default para no romper filas existentes
    op.execute("ALTER TABLE assets ADD COLUMN IF NOT EXISTS buffer_before_hours FLOAT NOT NULL DEFAULT 2.0")
    op.execute("ALTER TABLE assets ADD COLUMN IF NOT EXISTS buffer_after_hours FLOAT NOT NULL DEFAULT 2.0")
    op.execute("ALTER TABLE assets ADD COLUMN IF NOT EXISTS delivery_available BOOLEAN NOT NULL DEFAULT FALSE")
    op.execute("ALTER TABLE assets ADD COLUMN IF NOT EXISTS delivery_radius_km FLOAT NOT NULL DEFAULT 0.0")
    op.execute("ALTER TABLE assets ADD COLUMN IF NOT EXISTS delivery_cost_usd INTEGER NOT NULL DEFAULT 0")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS delivery_requested BOOLEAN NOT NULL DEFAULT FALSE")
    op.execute("ALTER TABLE bookings ADD COLUMN IF NOT EXISTS delivery_address TEXT")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS is_banned BOOLEAN NOT NULL DEFAULT FALSE")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS ban_reason VARCHAR")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'is_banned')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_index('ix_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_unique_constraint('password_reset_tokens_token_key', 'password_reset_tokens', ['token'])
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.create_index('ix_email_verification_tokens_token', 'email_verification_tokens', ['token'], unique=False)
    op.create_unique_constraint('email_verification_tokens_token_key', 'email_verification_tokens', ['token'])
    op.drop_column('bookings', 'delivery_address')
    op.drop_column('bookings', 'delivery_requested')
    op.drop_column('assets', 'delivery_cost_usd')
    op.drop_column('assets', 'delivery_radius_km')
    op.drop_column('assets', 'delivery_available')
    op.drop_column('assets', 'buffer_after_hours')
    op.drop_column('assets', 'buffer_before_hours')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_favorites_client_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_blocked_dates_asset_id'), table_name='blocked_dates')
    op.drop_table('blocked_dates')
    # ### end Alembic commands ###
